//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingSoldier.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post : IModel
    {
        public int Id { get; set; }
        public string PostTitle { get; set; }
        public string PostUrl { get; set; }
        public string PostContent { get; set; }
        public bool IsAQuestion { get; set; }
        public string Tags { get; set; }
        public string CategoryName { get; set; }
        public virtual Category Category { get; set; }
    }
}
