version: '3'

services:
  codingsoldier:
    image: codingsoldier
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "2350:2350"
  nginx:
    image: nginx
    ports:
      - "80:2350"