version: '3'

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    expose:
      - "2350"
  reverseproxy:
    build:
      context: .
      dockerfile: NginxDockerfile
    links:
      - website
    ports:
      - "8080:80"